[tool.poetry]
name = "miv-simulator"
version = "0.0.1a"
description = "Mind-in-Vitro simulator"
readme = "README.md"
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.4"
scipy = "^1.8.1"
mpi4py = "^3.1.3"
h5py = "^3.7.0"
Cython = "^0.29.30"
PyYAML = "^6.0"
sympy = "^1.10.1"
click = "^8.1.3"
networkx = "^2.8.4"
commandlib = "^0.3.5"
rbf = {git = "https://github.com/frthjf/RBF.git"}
neuroh5 = {git = "https://github.com/soltesz-lab/neuroh5.git"}
sphinx-click = {version = "^4.3.0", extras = ["docs"], optional = true}

[tool.poetry.dev-dependencies]
black = {extras = ["jupyter"], version = "^22.3.0"}
isort = {extras = ["colors"], version = "^5.10.1"}
mypy = "^0.950"
mypy-extensions = "^0.4.3"
pre-commit = "^2.19.0"
pylint = "^2.13.9"
pytest = "^7.1.2"
pyupgrade = "^2.32.1"
coverage = "^6.3.3"
pytest-html = "^3.1.1"
pytest-cov = "^3.0.0"

[tool.poetry.extras]
docs = ["sphinx-click"]

[tool.poetry.scripts]
# Main functions
make-h5types = { callable = "scripts.make_h5types:main", extras = [] }
measure-distances = { callable = "scripts.measure_distances:main", extras = [] }
generate-distance-connections = { callable = "scripts.generate_distance_connections:main", extras = [] }
generate-input-features = { callable = "scripts.generate_input_features:main", extras = [] }
generate-input-spike-trains = { callable = "scripts.generate_input_spike_trains:main", extras = [] }
generate-soma-coordinates = { callable = "scripts.generate_soma_coordinates:main", extras = [] }
distribute-synapse-locs = { callable = "scripts.distribute_synapse_locs:main", extras = [] }
# Analysis scripts
check-config = { callable = "scripts.analysis.check_config:main", extras = [] }
cut-slice = { callable = "scripts.analysis.cut_slice:main", extras = [] }
make-data-files = { callable = "scripts.analysis.make_data_files:main", extras = [] }
plot-biophys-cell-tree = { callable = "scripts.analysis.plot_biophys_cell_tree:main", extras = [] }
plot-cell-tree.py = { callable = "scripts.analysis.plot_cell_tree:main", extras = [] }
plot-coords-in-volume = { callable = "scripts.analysis.plot_coords_in_volume:main", extras = [] }
plot-network-clamp = { callable = "scripts.analysis.plot_network_clamp:main", extras = [] }
plot-spike-raster = { callable = "scripts.analysis.plot_spike_raster:main", extras = [] }
plot-state = { callable = "scripts.analysis.plot_state:main", extras = [] }
query-cell-attrs = { callable = "scripts.analysis.query_cell_attrs:main", extras = [] }
read-spikes = { callable = "scripts.analysis.read_spikes:main", extras = [] }
run-network = { callable = "scripts.analysis.run_network:main", extras = [] }
sample-cells = { callable = "scripts.analysis.sample_cells:main", extras = [] }
show-h5types = { callable = "scripts.analysis.show_h5types:main", extras = [] }


[build-system]
requires = ["poetry_core>=1.0.0", "cython"]
build-backend = "poetry.core.masonry.api"


[tool.black]
# https://github.com/psf/black
line-length = 80
target_version = ["py37"]
# include = 'src\/.*\.pyi?$|tests\/.*\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist'
  )/
)
'''

[tool.isort]
# https://github.com/timothycrosley/isort/
known_typing = "typing,types,typing_extensions,mypy,mypy_extensions"
sections = "FUTURE,TYPING,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
include_trailing_comma = true
default_section = "FIRSTPARTY"
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80

[tool.pylint.'MESSAGES CONTROL']
disable = "protected-access, import-outside-toplevel, too-few-public-methods"

