[tool.poetry]
name = "miv-simulator"
version = "0.0.1a"
description = "Mind-in-Vitro simulator"
readme = "README.md"
authors = []

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.4"
scipy = "^1.8.1"
mpi4py = "^3.1.3"
h5py = "^3.7.0"
Cython = "^0.29.30"
PyYAML = "^6.0"
sympy = "^1.10.1"
click = "^8.1.3"
networkx = "^2.8.4"
commandlib = "^0.3.5"
rbf = {git = "https://github.com/frthjf/RBF.git"}
neuroh5 = {git = "https://github.com/soltesz-lab/neuroh5.git"}

[tool.poetry.dev-dependencies]
black = {extras = ["jupyter"], version = "^22.3.0"}
isort = {extras = ["colors"], version = "^5.10.1"}
mypy = "^0.950"
mypy-extensions = "^0.4.3"
pre-commit = "^2.19.0"
pylint = "^2.13.9"
pytest = "^7.1.2"
pyupgrade = "^2.32.1"
coverage = "^6.3.3"
pytest-html = "^3.1.1"
pytest-cov = "^3.0.0"

[tool.poetry.scripts]
# Main functions
make_h5types = "scripts.make_h5types:main"
measure_distances = "scripts.measure_distances:main"
generate_distance_connections = "scripts.generate_distance_connections:main"
generate_input_features = "scripts.generate_input_features:main"
generate_input_spike_trains = "scripts.generate_input_spike_trains:main"
generate_soma_coordinates = "scripts.generate_soma_coordinates:main"
distribute_synapse_locs = "scripts.distribute_synapse_locs:main"

# Analysis scripts
check_config = "scripts.analysis.check_config:main"
cut_slice = "scripts.analysis.cut_slice:main"
make_data_files = "scripts.analysis.make_data_files:main"
plot_biophys_cell_tree = "scripts.analysis.plot_biophys_cell_tree:main"
plot_cell_tree.py = "scripts.analysis.plot_cell_tree:main"
plot_coords_in_volume = "scripts.analysis.plot_coords_in_volume:main"
plot_network_clamp = "scripts.analysis.plot_network_clamp:main"
plot_spike_raster = "scripts.analysis.plot_spike_raster:main"
plot_state = "scripts.analysis.plot_state:main"
query_cell_attrs = "scripts.analysis.query_cell_attrs:main"
read_spikes = "scripts.analysis.read_spikes:main"
run_network = "scripts.analysis.run_network:main"
sample_cells = "scripts.analysis.sample_cells:main"
show_h5types = "scripts.analysis.show_h5types:main"


[build-system]
requires = ["poetry_core>=1.0.0", "cython"]
build-backend = "poetry.core.masonry.api"


[tool.black]
# https://github.com/psf/black
line-length = 80
target_version = ["py37"]
# include = 'src\/.*\.pyi?$|tests\/.*\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist'
  )/
)
'''

[tool.isort]
# https://github.com/timothycrosley/isort/
known_typing = "typing,types,typing_extensions,mypy,mypy_extensions"
sections = "FUTURE,TYPING,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
include_trailing_comma = true
default_section = "FIRSTPARTY"
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80

[tool.pylint.'MESSAGES CONTROL']
disable = "protected-access, import-outside-toplevel, too-few-public-methods"

