# Common definitions used in model configuration of neuron and network models
SWC Types:
  soma:   1
  axon:   2
  basal:  3
  apical: 4
  trunk:  5
  tuft:   6
  ais:    7
  hillock: 8
Synapse Types:
  excitatory:    0
  inhibitory:    1
  modulatory:    2
Synapse Mechanisms:
  AMPA:    0
  GABA_A:  1
  GABA_B:  2
  NMDA:    30
Layers:
  SO:    0  ## Oriens
  SP:    1  ## Pyramidale
  SL:    2  ## Lucidum
  SR:    3  ## Radiatum
  SLM:   4  ## Lacunosum-moleculare
Populations:
  PYR:  100
  PVBC:  101
  OLM:  102
Input Selectivity Types:
  random: 0
  ripple: 1
