## Model configuration of microcircuit network
Model Name: Microcircuit_PYR
Dataset Name: Microcircuit
Definitions: !include Definitions.yaml
Global Parameters: !include Global.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Connection Generator: !include Microcircuit_Connections.yaml
Recording: !include Recording.yaml
Cell Data: MiV_Cells_Microcircuit_20220404.h5
Connection Data: MiV_Connections_Microcircuit_20220404.h5
#Stimulus: !include Input_Configuration.yaml
Analysis: !include Analysis_Configuration.yaml
Cell Types:
  PYR:
    template: PoolosPyramidalCell
    synapses:
      density: !include PYR_synapse_density.yaml
  OLM:
    template: OLMCell
    synapses:
      density: !include OLM_synapse_density.yaml
  PVBC:
    template: PVBasketCell
    synapses:
      density: !include PVBC_synapse_density.yaml
