## Information needed: CA2 projections and strengths needed, NMDA unit strengths, IS 
## TODO:
## PVBC:
##  - excitatory connections on soma in SP
##  - inhibitory connections on PVBC basal SO
## SPYR:
##  - CA2 connections in SR
## DPYR:
##  - excitatory connections on soma in SP
##  - CA2 connections in SR
Synapse Mechanisms:
  AMPA: LinExp2Syn 
  NMDA: FacilNMDA
  GABA_A: LinExp2Syn
  GABA_B: LinExp2Syn
Synapse Parameter Rules: !include Synapse_Parameter_Rules.yaml
Axon Extent: !include Axon_Extent.yaml
Connection Velocity: !include Connection_Velocity.yaml
Synapses:
  PYR:
    PYR:
      type: excitatory
      sections: [basal, apical]
      layers: [SO, SR]
      proportions: [1.0, 1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.0001
        NMDA:
          g_unit: 0.0001
    PVBC:   
      type: inhibitory
      sections: [soma, basal, apical]
      layers: [SP, SO, SR]
      proportions: [1.0, 1.0, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.30
          tau_decay: 6.2
          e: -60
          g_unit: 0.000186
  PVBC:
    PYR:
      type: excitatory
      sections: [apical, basal]
      layers: [SR, SO]
      proportions: [1.0, 1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.001
    PVBC:   
      type: inhibitory
      sections: [soma, apical, basal]
      layers: [SP, SP, SO]
      proportions: [1.0, 1.0, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.08
          tau_decay: 4.8
          e: -60
          g_unit: 0.001
