## Model configuration of dentate gyrus network
Model Name: Network_Clamp_PYR
Dataset Name: Microcircuit_Subset
Definitions: !include Definitions.yaml
Geometry: !include Geometry.yaml
Random Seeds: !include Random.yaml
Cell Data: Microcircuit_PYR_selection_gid_48041.h5
Connection Data: Microcircuit_PYR_selection_gid_48041.h5
Connection Generator: !include Microcircuit_Connections.yaml
Recording: !include Recording.yaml
Stimulus: !include Input_Configuration.yaml
Analysis: !include Analysis_Configuration.yaml
## Cell types for dentate gyrus model
Cell Types:
  PYR:
    template: PoolosPyramidalCell
    synapses:
      density: !include PYR_synapse_density.yaml
  OLM:
    template: OLMCell
    synapses:
      density: !include OLM_synapse_density.yaml
  PVBC:
    template: PVBasketCell
    synapses:
      density: !include PVBC_synapse_density.yaml
  STIM:
    template: VecStim
    spike train:
      namespace: Input Spikes
      attribute: Spike Train

