soma:
  cable:
    L: 50.0      #Length of soma (um)
    diam: 50.0   #Diameter of soma (um)
    Ra: 150.0
    cm: 1.41
  pas:
    g: 4.0e-5
    e: -60.0

# Spiking conductances    
  na3:
    gbar: 0.04
  kdr:
    gkdrbar: 0.01
  kap:
    gkabar: 0.07
    
# Firing pattern conductances 
  km:
    km: 0.0006
  kd:
    gkdbar: 0.00045
  kd_slow:
    gkdbar_kd_slow: 0
  cal:
    gcatbar: 0.001
  can:
    gcatbar: 0.001
  cat:
    gcatbar: 0.001
  cagk:
    gbar: 0.0001
  cacum:
    depth: 25.0
    

