name: CI

on:
  #push: # Add these lines after public release
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest #${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8"] # , "3.9", "3.10"]
        os: [ubuntu-latest] #, macos-latest, windows-latest] # Run macos tests if really required, since they charge 10 times more for macos
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          - os: macos-latest
            path: ~/Library/Caches/pip
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache
    steps:
      - uses: actions/checkout@v2
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: mpich
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      # Test MiV-OS using pytest
      - name: Run tests
        run: |
          make test
